### ISSUE TITLE
Feature: Add a site list instead of 503

### ISSUE THREAD

**Issue by frankamp** [jwilder/nginx-proxy#788] opened 2017-04-06 19:10 UTC
I use something like this to display a site list instead of a 503. It might be a nice feature, not enabled by default.
in  `nginx.tmpl`

replace the default site's `return 503`

with

```
default_type text/html;
return 200 '<html><head><meta charset="utf-8"/><title>Services</title></head><body>
    <h1>Site List</h1>
    <ul>
    {{ range $host, $containers := groupByMulti $ "Env.VIRTUAL_HOST" "," }}
    {{ $proto := or (first (groupByKeys $containers "Env.VIRTUAL_PROTO")) "http" }}
    <li><a href="{{ $proto }}://{{ $host }}">{{ $host }}</a></li>
    {{ end }}
    </ul>
    </body></html>';
```

**Comment by nosovk** [comment] 2017-07-11 19:52
Probably it should be optional feature, cause it's good for stage, but not for prod

**Comment by alexanderadam** [comment] 2017-10-09 12:15
That's a neat idea. It might also help people debugging [instead of them opening issues with generic 503 in the title](https://github.com/jwilder/nginx-proxy/search?q=503&type=Issues&utf8=%E2%9C%93).

**Comment by thaJeztah** [comment] 2017-10-09 12:21
Looks related / duplicate of https://github.com/jwilder/nginx-proxy/issues/146 (+1 to not making a default for reasons mentioned in the linked issue)

**Closed** 2018-03-24 03:35 UTC
