### ISSUE TITLE
Http2 not working with active tls 

### ISSUE THREAD

**Issue by bernex** [jwilder/nginx-proxy#543] opened 2016-08-24 09:59 UTC
Certificate is installed and correctly working in browser without errors.
But I see in Chrome console - http/1.1 mode.

How enable h2?

**Comment by jwilder** [comment] 2016-08-25 00:07
`http2` should be enabled already by default.  Are you sure your are running an updated image?

**Comment by bernex** [comment] 2016-08-25 05:54
yes, I see `ssl http2 ;` in generated config, but not working.

**Comment by wader** [comment] 2016-08-25 10:31
I think this is because newer versions of chrome requires ALPN and nginx-proxy at the moment is linked with an old verison of openssl (pre 1.0.2 i think) that does not support it.

https://www.nginx.com/blog/supporting-http2-google-chrome-users/

**Comment by ihor-sviziev** [comment] 2016-08-25 17:10
@wader thank you!
Waiting for nginx container update with updated openssl lib.

**Comment by yannisc** [comment] 2016-08-29 12:15
Yes, alpine based nginx uses the newer version of openssl and provides ALPN. It would be great if this project switched to alpine. This [project](https://github.com/ej52/alpine-nginx-proxy) uses this approach, but it would be great if the "official" nginx proxy supported it.

**Comment by jwilder** [comment] 2016-08-29 16:07
`latest` is now using `nginx:1.11.3`.  This might be fixed now.

**Comment by wader** [comment] 2016-08-29 16:24
@jwilder i think the problem is that debian:jessie has a too old openssl
```
root@89c7f36ed7d2:/app# dpkg -l | grep openssl
ii  openssl                   1.0.1t-1+deb8u2          amd64        Secure Sockets Layer toolkit - cryptographic utility
```

**Comment by jwilder** [comment] 2016-08-29 16:36
Hmm.  Looks like there is an `1.11.3-alpine` official image. I have `alpine` versions of `docker-gen` and could create one for `forego` if needed.  I'm not sure what would break by switching base images off-hand though.

**Comment by ihor-sviziev** [comment] 2016-08-31 04:42
@jwilder could you create special tag with Alpine Linux, same as nginx - <version>-alpine ?
It would be good alternative

**Comment by kachkaev** [comment] 2016-10-18 14:23
I'm using nginx+docker gen and after upgrading from nginx 1.11.0 to 1.11.5-alpine I finally started seeing `h2` instead of `http/1.1` in Chrome devtools. Thanks a lot of the hint Jason!

**Comment by sandrodz** [comment] 2017-01-29 21:38
is alpine tag usable in production?

**Comment by sandrodz** [comment] 2017-03-12 19:38
#349 is duplicate at this point. should be closed.

**Comment by jwilder** [comment] 2017-03-13 16:15
The alpine images apparently work with https.  There is an `alpine` tag for `nginx-proxy` as well as an `alpine` tag for `nginx`.

**Closed by jwilder** 2017-03-13 16:15 UTC

**Comment by sischnei** [comment] 2017-03-18 09:09
Thanks for the hint - would be really cool to include this on the front page README!

**Comment by matt-hh** [comment] 2017-03-18 09:20
@sischnei could you please provide a pull request with your changes for README.md?

**Comment by sischnei** [comment] 2017-03-18 09:55
@matt-hh don't have much experience with pull requests on GIT, hopefully did it right! See #770
